### ISSUE TITLE
Looks interesting, but I'm unable to install it for the last ES version...

### ISSUE THREAD

**Issue by apolonsky** [lindstromhenrik/elasticsearch-analysis-file-watcher-synonym#1]

**Comment by apolonsky** [comment]
Thanks for the quick update! Unfortunately, I'm still having trouble. When I try to install the plugin using the bin/plugin command, I get the following errors:

[root@localhost elasticsearch-0.90.7]# bin/plugin --url https://github.com/linds                                                                                        tromhenrik/elasticsearch-analysis-file-watcher-synonym --install synonym --verbose
-> Installing synonym...
Trying https://github.com/lindstromhenrik/elasticsearch-analysis-file-watcher-synonym...
Downloading ...DONE
failed to extract plugin [/usr/local/elasticsearch-0.90.7/plugins/synonym.zip]:                                                                                         ZipException[error in opening zip file]

Or, if give the URL of the zip file:

[root@localhost elasticsearch-0.90.7]# bin/plugin --url https://github.com/lindstromhenrik/elasticsearch-analysis-file-watcher-synonym/archive/master.zip --install synonym --verbose
-> Installing synonym...
Trying https://github.com/lindstromhenrik/elasticsearch-analysis-file-watcher-synonym/archive/master.zip...
Downloading .DONE
Installed synonym into /usr/local/elasticsearch-0.90.7/plugins/synonym
Plugin installation assumed to be site plugin, but contains source code, aborting installation...

If I simply download and unzip the file in the plugins directory, and then restart ES, the plugin does not appear declared in the plugin list.

Any ideas?

Thanks a lot for your help,
Alexander

**Comment by lindstromhenrik** [comment]
At the moment you need to build the plugin yourself:
- Clone this repo with git clone git://github.com/lindstromhenrik/elasticsearch-analysis-file-watcher-synonym.git
- Run: mvn clean package
- Install the plugin: /path/to/elasticsearch/bin/plugin -install analysis-file-watcher-synonym -url file:///$PWD/target/elasticsearch-elasticsearch-file-watcher-synonym-0.90.9.zip

/Henrik

**Comment by apolonsky** [comment]
Ah, I see. Thanks!

On Tue, Dec 31, 2013 at 11:39 AM, Henrik Lindström <notifications@github.com
